// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace OrderManagement.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StateId");

                    b.Property<string>("AbbAbreviaton")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("state");

                    b.HasData(
                        new
                        {
                            Id = new Guid("739561c4-8ba5-4b56-aa11-9891882668f6"),
                            AbbAbreviaton = "AL",
                            Name = "Alabama"
                        },
                        new
                        {
                            Id = new Guid("1fbdc0fa-d3cb-47b0-86f8-bb11a46cbfba"),
                            AbbAbreviaton = "AK",
                            Name = "Alaska"
                        },
                        new
                        {
                            Id = new Guid("2d715fc3-1687-4723-a3d6-bb1e2b9fcb37"),
                            AbbAbreviaton = "AZ",
                            Name = "Arizona"
                        },
                        new
                        {
                            Id = new Guid("13c1d98a-9420-4b20-ad16-105d73b9dd69"),
                            AbbAbreviaton = "AR",
                            Name = "Arkansas"
                        },
                        new
                        {
                            Id = new Guid("32331d91-5b4e-4b20-8ea4-14062bcf1517"),
                            AbbAbreviaton = "CA",
                            Name = "California"
                        },
                        new
                        {
                            Id = new Guid("9a4aa09b-ce6e-4cc5-82dc-6928e4645df7"),
                            AbbAbreviaton = "CO",
                            Name = "Colorado"
                        });
                });

            modelBuilder.Entity("Entities.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SupplierId");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("supplier");

                    b.HasData(
                        new
                        {
                            Id = new Guid("391f8f7d-5f1d-46e1-bcfd-1148422342b1"),
                            AddressLine1 = "990 ABC XYZ, AdressLine1 ",
                            AddressLine2 = "USA",
                            City = "Huntsville",
                            Name = "ABC_Solutions Ltd",
                            PostalCode = "87474",
                            StateId = new Guid("739561c4-8ba5-4b56-aa11-9891882668f6")
                        },
                        new
                        {
                            Id = new Guid("679c685e-2e9c-4c01-a786-d19e7fd10b48"),
                            AddressLine1 = "120 ABC XYZ, AdressLine1 ",
                            AddressLine2 = "USA",
                            City = "Los Angeles",
                            Name = "XYZ_Solutions Ltd",
                            PostalCode = "94992",
                            StateId = new Guid("32331d91-5b4e-4b20-8ea4-14062bcf1517")
                        },
                        new
                        {
                            Id = new Guid("b4d1f629-0218-4629-9648-aa11451e64e3"),
                            AddressLine1 = "120 ABC XYZ, AdressLine1 ",
                            AddressLine2 = "USA",
                            City = "Denver",
                            Name = "GHJ_Solutions Ltd",
                            PostalCode = "80014",
                            StateId = new Guid("9a4aa09b-ce6e-4cc5-82dc-6928e4645df7")
                        },
                        new
                        {
                            Id = new Guid("87e1244c-01f6-45f5-a080-2bab9e0319bb"),
                            AddressLine1 = "120 ABC XYZ, AdressLine1 ",
                            AddressLine2 = "USA",
                            City = "Little Rock",
                            Name = "New_Solutions Ltd",
                            PostalCode = "80014",
                            StateId = new Guid("13c1d98a-9420-4b20-ad16-105d73b9dd69")
                        });
                });

            modelBuilder.Entity("Entities.Models.Supplier", b =>
                {
                    b.HasOne("Entities.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });
#pragma warning restore 612, 618
        }
    }
}
